tunnel: 2bfb4869-d2fa-4517-a654-929d432f9a26
credentials-file: /etc/cloudflared/credentials.json
origin-cert: /etc/cloudflared/cert.pem
ingress:
  - hostname: mqtt.synkroarg.work
    service: tcp://mosquitto_proyecto:1883
  - hostname: mqttws.synkroarg.work
    service: http://mosquitto_proyecto:9001
  - hostname: "*.synkroarg.work"
    service: http://npm_proyecto:80
  - service: http_status:404